### PR TITLE
Implementation of detecting existing trailers

### LINKED ISSUE #9: Suggestion - Check if trailer exists in the folder already?
So I'm curious if it's possible to implement a change that checks to see if the trailer file already exists in a folder? if it does, then the process simply skips downloading the trailer. Currently it seems like it downloads the trailer file again and overwrites the existing file. 

Doing this type of check would let me essentially run the download_all process on a weekly schedule basis to ensure my trailers are all in place but not having to download the same ones again and again and again.

Thanks for a great app!

### PR DESCRIPTION
**Pull request by Ahsome**
Script now checks to see if any file exists in the folder that matches whatever the trailer was to be downloaded in (e.g. Movie-trailer.mp4)

It also checks across file extensions, so will not download a trailer if Movie-trailker.mkv exists

No code to check if the existing file is a video, so a file Movie-trailer.docx would also stop the trailer from downloading. Not sure if this needs to be extended? This should fix #9

### CODE REVIEW

**Comment by danz0l** [comment]
Ok i have the script saving to a sub directory called Trailers within each movie directory.

I wanted all my trailers to have the filename Trailer.mp4 so i modified the script a little to just save this filename in each sub directory.

Does your modification now check to see if there is a Trailer.mkv file present and if so skip ? 

My hack is hard coded for the Trailer.mp4 filename so it would be fantastic if i could get a config way into the script so i don't have to hard code on each new update. 

Great work btw.

**Comment by danz0l** [comment]
Sorry to clarify, in some directories i have the mkv extension present as i already downloaded some trailers. At the moment the script ignores seeing that and i end up with two trailers, Trailer.mp4 and Trailer.mkv.

**Comment by Ahsome** [comment]
One of the things I'd like to add in an update is make it so you can specify the filename beyond just "movie-trailer" or "movie"

Until that though, it's absolutely possible for the script to skip if it's a Trailer.mkv, it just depends where you hard codes it

Can you show me where and how you hard coded it?

Also THANK YOU!

**Comment by Ahsome** [comment]
If you want to hard code it currently, until a future update allows you to do this via **settings.ini**, go to line 235:
```python
# If append_filenames setting is set, add -trailer to the filename.
        if settings['append_filenames'] is not None and settings['append_filenames'].lower() == 'true':
            filename = arguments['title'].replace(':', '-')+' ('+arguments['year']+')-trailer.mp4'
        else:
            filename = arguments['title'].replace(':', '-')+' ('+arguments['year']+').mp4'
```

Modify the code such that it says this now

```python
# If append_filenames setting is set, add -trailer to the filename.
        if settings['append_filenames'] is not None and settings['append_filenames'].lower() == 'true':
            filename = 'Trailer.mp4'
        else:
            filename = 'Trailer.mp4'
```

**Comment by danz0l** [comment]
That's currently how i had it hard coded mate, and it works. Just a pain to
hard code on each update.

My limited python scripting had me try and settings.ini in based on the
existing code and i couldn't get it to work fully lol

Great that there is two developers working on this now, i use the script
daily and although i have to manually intervene and update some of the
older trailers (or upgrade manually to better quality) my success rate has
been probably around 70%

**Comment by Ahsome** [comment]
That's awesome! I am currently making it possible to manually set a constant name for the trailer in settings.ini, so you shold find it much easier without needing to update per code. My python scripting is suuuuuper limited too, I've just been learning as I go with this (this repo has been a really fun way to learn Python)

If it is at all possible, can you give examples of what movies you needed to do manual intervention? As well as other stuff you would like to see implemented

**Comment by danz0l** [comment]
I update around 15 movies a day so I'll send a list of failed ones that i
know have trailers on tmdb to see why it doesn't find them.

I know what you mean about using this repo for python learning, i looked
through the code and it was well structured and i understood most of it. I
wish i could find the time to learn more.

Mmmmmmm features. Ok i have a few possibilities but neither will be easy to
implement

1. HD Trailerer downloading.

This code could potentially come from the couch potato trailer downloader
though ?

2. Source better quality trailers on YouTube.

This one isn't an easy one I'm thinking. The code i think uses tmdb api to
check for a match and based on that match downloads the associated trailer
if present. However a great deal of tmdb trailers are sub par (likely the
best they could source at the time and rarely updated).

I like my trailers in the best i can get and certainly prefer HD over 360p.
Manually searching YouTube usually gets me a HD updated trailer or at the
very least a better 480p trailer than tmdb.

As i say that's not an easy implementation though as lots of logic would
have to go in the code and i could see lots of false positives issues
arising there.

**Comment by Ahsome** [comment]
The code is structured really nicely, so it's been a breeze so far adding stuff (besides me screaming at Python 2 and how it handles UNICODE). Definitely send the list of ones that fail, that way we can see what's most likely the culprit

I'll definitely try looking at those other two as well, especially getting better quality trailers on YouTube (given the subpar-ness of TMDb sometimes). It's still a lot better than what natively runs on Plex

Thank you though! This is going to be a fun time

**Comment by Ahsome** [comment]
YUP, makes sense (how did I leave this to be an option). I'll fix this up as soon as possible

**Comment by Ahsome** [comment]
Wait @airship-david I think you misinterpreted the code. What it does is take the filename that _we_ specified to save the trailer into. This will always be "name-we-want-trailer".mp4, because we are the ones choosing to download the trailer as mp4

i.e. if the user wanted Shrek, and chose to append trailer, `filename = "Shrek (2001)-trailer.mp4"
We then take the section without mp4 (which will always be mp4), and check if any files contain "Shrek (2001)-trailer"

```python
for name in os.listdir(arguments['directory']):
            if filename[:-4] in name:
                return
```

So this should work for any extension saved, even if its not 3 letters, as long as the name we choose to save the trailer will be 3 digits (always since we download as mp4)

**Comment by Ahsome** [comment]
I'm just going to stop touching git for a while now... **sigh**

**Comment by airship-david** [comment]
Ah yeah I definitely misunderstood. Sorry about that! This pull request has now gone off the rails though :(. Much of the code now seems to be related to testing and YouTube Rentals trailers. Going to close this and manually add the original code to the develop branch.
Screen Shot 2019-06-19 at 9 11 44 AM

**Comment by Ahsome** [comment]
Yup okay that makes sense! Hopefully I don't mess up the other pull requests...

Any idea when you'd be able to finish merging the pull requests?

**Pull request closed without merging**
