### PR TITLE
Automated FFMpeg detection

### PR DESCRIPTION
**Pull request by Ahsome**
Code can now attempt to find FFmpeg if setting is empty in settings.ini, or the setting is not valid

Code will check if the automatic one found it correctly. If not, state to user and tell to make sure FFmpeg is installed or pointed to the right direction

### CODE REVIEW

**Comment by airship-david** [comment]
FFmpeg detection is a great idea and good call on removing ffmpeg from requirements.txt (totally missed that). Need some of this to be cleaned up before we can merge it into the rest of the code though. For the .exe file, unfortunately I have no interest in adding custom support for any particular os but especially windows lol

**Comment by Ahsome** [comment]
If that's the case, should I remove the code checking for FFmpeg.exe in the current directory of the code, or should I keep it? It's Windows specific since Windows allows it more easily copy a ".exe" into the directory?

If we don't do it, the README would need to state to specify the path for FFmpeg for Windows, as installing FFmpeg on Windows does not add it to "PATH"

**Comment by Ahsome** [comment]
Hopefully this is a bit cleaner now?

**Comment by Ahsome** [comment]
Wait, is youtube-dl able to find ffmpeg automatically?

**Comment by airship-david** [comment]
Yes exactly. Figured this was a simpler approach. Let me know if you run into any issues with this method.

**Pull request closed without merging**
