### PR TITLE
Allowed the use of UNICODE in filename

### PR DESCRIPTION
**Pull request by Ahsome**
Allows UNICODE in filename, for special names (such as Pokemon). Otherwise, cannot work as it uses ASCII

### CODE REVIEW

**Comment by Ahsome** [comment]
Need to do more testing

**Comment by Ahsome** [comment]
Now should successfully be able to generate Trailers, even if the Movie name containts characters not defined by ASCII

**Comment by airship-david** [comment]
Awesome! This was on my to do list. I’m out of town right now but I’ll merge it when I get back. Cheers!

**Comment by Ahsome** [comment]
Thank you! This is my first ever pull request so it was exciting 😊. Is it alright if I code other suggestions, or should I just keep in my fork?

**Comment by airship-david** [comment]
That’s awesome! Please continue to add any features you think would be useful or I am open to requests. This project consistently gets a lot of downloads so I’m all for helping the community. The only feature I’m really against is adding tv shows. Based off my own experience, relevancy will fall off a cliff if we move in that direction so I want to keep this project geared towards movies. Thanks!

**Comment by Ahsome** [comment]
AWESOME, I understand the part about television completely. I'll try adding any new and smaller features that I can think of!

**Comment by Ahsome** [comment]
Okay I'm going to close this commit, because I've realised the code is only Unix specific, plus it's essentially a hack. I will redo a proper pull request

**Pull request closed without merging**
