### PR TITLE
Manual trailer name

### PR DESCRIPTION
**Pull request by Ahsome**
Now, if a manual trailer name is added to settings.ini, all trailers will be saved with that. This would replace generating a name based on the name of the film, and would ignore appending.

### CODE REVIEW

**Comment by danz0l** [comment]
Brilliant. How do i pull your additions to test ?

**Comment by Ahsome** [comment]
Thank you! Right now to try on this repository @airship-david has to approve and merge the changes, which he (hopefully) will do soon

However, you can still test this now by cloning my fork of this repository:
`git clone https://github.com/Ahsome/Trailer-Downloader.git`

Then **checkout** the branch containing these changes:
`git checkout manual-trailer-name`

Then your copy should be the same as @airship-david's, plus the ability to set the trailer manually. All the features I've added are in separate branches, so checkout to whatever branch you want to test them. You can list all the branches via:
`git branch -a`

Once @airship-david accepts them, you should be able to just use the normal repo and it will have all the features together

**Comment by danz0l** [comment]
Ok.

I'll likely test then when they are all merged on the pull then report back
any issues.

So far today the script has failed to find trailers for the following
(Folders named as below)

Over the Hedge (2006)
Shrek (2001)

Each has a trailer in tmdb

**Comment by Ahsome** [comment]
Thank you! That would be extremely appreciated
And hmm, that is interesting. How is the actual movie file named for both films?

**Comment by danz0l** [comment]
From what i understood of the script it uses the directories for lookups
but here are the filenames

Over the Hedge (2006) Bluray-1080p x265.AAC.mkv

Shrek (2001) Bluray-1080p x265.AAC.mkv

I thought it might be a timeout of the tmdb api but repeatedly running the
script results in the same behaviour.

I've also tried it without the quality at the end of the filename

Shrek (2001) Bluray-1080p.mkv

Same result.

**Comment by Ahsome** [comment]
Are you using download_all.py, and you're passing **-d** to the folder containing Shrek (2001) and Over the Hedge (2006)?

**Comment by danz0l** [comment]
Yes  in this format

 python Trailer-Downloader/download_all.py --directory PATH.TO.DIRECTORYS

**Comment by Ahsome** [comment]
Yup, I just tested and realised why. Both of those films do not exist on Apple's trailers, so it checks TMDb. However, for both films, the quality of the trailer is 360p. This is below the minimum requirement set in settings.ini, which is 480p

Options from now are
1. Let settings.ini to be lower, and download these at low quality
2. Edit the script so it checks YouTube for any that are higher quality first that are not listed on TMDb

**Comment by danz0l** [comment]
Ah yes that's logical.

Reliance on tmdb is obviously the easiest way to get trailers, but they
really do have done shocking quality ones lol

But as you say, still better than Plex pass trailer quality.

**Comment by Ahsome** [comment]
I've got one idea that might get good quality trailer for older films, let me just try...

**Comment by airship-david** [comment]
Hey guys! I just got back from my trip late last night so I’m going to try to get caught up on these commits and pull requests today. I think there are a few ways for me to clean up some other code as well. I put this project together pretty quickly after discovering that the trailer addict agent was shut down and I was pretty excited about it so I’m very happy that this has seemingly been useful for so many other people and that it has interested you guys enough to dive into the code. Little projects like this are the reason I love programming so much. @danz0l you are spot on with there being some poor quality trailers on tmdb and this being the result of trailers not being updated often. I love tmdb and I think the best way for us to combat that is to make those changes on tmdb ourselves. This is what I have done for trailers that I wasn’t able to find and doing that increased my success rate to over 99%. It usually takes up to a day for those changes to hit their api and allow this script to download them but it is great for the community since it ensures that the next person will get the trailer when they run this script too. Beyond that, I think there is value in adding a third source but maybe that is a bit lower on the priority list. Cheers!

**Comment by Ahsome** [comment]
Hope you like the changes I've been able to do @airship-david! It's been a blast to do this

@danz0I, check the newest pull request I did. I was successfully able to get that idea to work, and it is _awesome_

**Comment by danz0l** [comment]
Wow the new YouTube trailer sounds really really exciting, i can't wait to
try that.

Maybe do a development branch with all the commits and then i can run it
extensively and report back.

And welcome back David, glad you finally getting some help and more
feedback on this excellent python script. This and the videoslimer python
set of scripts by binhex have got my library into really tip top condition.

David, good point regards the terrible 360p trailers on tmdb. I'll start
pushing the more higher quality ones when i find them for the good of the
community.

Another option that might be viable is simple multithreading the downloads.
As it stands the Apple downloader is very slow but does result in the best
possible quality, but this stalls the script awaiting to test and download
the next trailer. If we could multithread at some point we could download
say 2 at a time, more important I'd say for the download_all script. Not
sure if Apple would pose a limit on that however.

Great work both, brilliant scripts and happy to test and help anyway i can

**Comment by airship-david** [comment]
@Ahsome This is a good approach but I think I'm going to move another direction on this one. I think I'll remove the append_filenames option entirely and add new a formatting setting instead where users can specify how the files should be named using variables for the title and year and whatever else they would like included in there.

**Comment by airship-david** [comment]
Custom formatting added to develop branch.

**Comment by Ahsome** [comment]
Yup, I was considering that method to (similar to how Sonarr and Radarr does it), but I was scared it would be extra added complexity. Definitely refer this method though

**Pull request closed without merging**
