### PR TITLE
YouTube Official Movie Scraper

### PR DESCRIPTION
**Pull request by Ahsome**
YouTube allows the ability to rent and buy movies directly from their website. If you attempt to watch the movie without renting, however, it plays a trailer of the film curated by YouTube rather than the full film itself

The scraper attempts to download the trailer YouTube shows before purchasing a film. This is almost always very high quality, as it is YouTube trying to sell their platform. These are better and more recent than TMDb's movies, so are attempted before the film

Although all movies I tested perfectly downloaded the correct film (including obscure ones, and ones where TMDB only had 360p), there has not been a check to make sure the video download matches the same name as the film

Some editing had to be made as the URL shown in YouTube's page is not downloadable via youtube-dl. However, converting it to its shorten form does allow it be downloaded perfectly

### CODE REVIEW

**Comment by danz0l** [comment]
Having looked at the trailers for the rentals, omg, the quality, especially
for older films, is just simply outstanding.

I'm super excited to try this.

What a fantastic idea. Brilliant

**Comment by airship-david** [comment]
This is a brilliant idea @Ahsome. As long as we can come up with a way to match the title this may be the perfect solution to getting a third source and improving both quality and success rate. Cheers!

**Comment by Ahsome** [comment]
Thank you guys so much! I'm very, _very_, glad I accidentally opened up a YouTube movie while testing. Otherwise I'd have no idea they would play a trailer before the film! I'll work on matching as soon as I can

**Comment by danz0l** [comment]
Very eager to test this function.

It led me to other providers to check to see if this could be expanded
further but Amazon uses a cryptic link that establishing the connection
with the trailer from one of their apps it appears and Google movies uses
the same provider that it appears itunes uses, playing an excerpt from the
movie instead of a trailer if they don't have the actual trailer  causing
some rather unimpressive trailer responses (i mean, a trailer should
explain within a few minutes what the actual movie is about, not play an
excerpt that explains nothing).

Btw i did look into hdtrailers.net but they appear to just curate quicktime
movies so that's already covered.

I'll continue to see if this can be expanded by further providers but the
YouTube find is a really really good one

**Comment by Ahsome** [comment]
Yes, absolutely if you can find any other sources let us know! I really did just accidentally stumbled on the fact that YouTube provides this, so I'm sure this trick can be used for a lot more sources of Trailers (although I haven't been able to find anyone else on GitHub using this trick)

That's why I didn't look into HD-trailers, since they just curate movies from Apple (which this already gets) and Yahoo! links, which never work properly. Obviously not every film will have a trailer, but hopefully we can make it that every film that _does_ have a trailer, we can get

@danzl0 is it possible that if I attach the download.py script here for you to test on your side? Just make sure to rename your own copy to backup, because I'd love to see if this also works on your side as well (given this scrapes HTML, I'm really not sure if it works between devices)

**Comment by danz0l** [comment]
Yes more than happy to test on a separate install. I use Ubuntu 18.04
headless and based in the UK so it will be region and os tested

**Comment by danz0l** [comment]
Might be an idea to put a quick text code in telling me if it's coming from
YouTube though so i can see where the source comes from ?

**Comment by Ahsome** [comment]
That's awesome! That kind of testing would be critical for testing
No need for the text code, this version of download.py has been edited to disable downloading from Apple trailers or TMDb. So if it passes and downloads, it will solely be because of YouTube (I think this is what you're asking for?)

Remember to call `python -m pip install -r requirements.txt`. This is because this function uses two new libraries to scrap the HTML

[Trailer-Downloader.zip](https://github.com/airship-david/Trailer-Downloader/files/3305080/Trailer-Downloader.zip)

**Comment by danz0l** [comment]
Ok will test and report back

**Comment by Ahsome** [comment]
Please check again, I accidently send the wrong zip, sorry...

**Comment by danz0l** [comment]
Ok so i redownload the same attachment ?

**Comment by Ahsome** [comment]
Yup! The attachment has been changed, just has the same name

**Comment by danz0l** [comment]
unix struggling with one of the requirements

`python -m pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: tmdbsimple==2.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: youtube-dl==2019.4.24 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2019.4.24)
Requirement already satisfied: ffmpeg==1.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (1.4)
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.22.0)
Collecting bs4==4.7.1 (from -r requirements.txt (line 5))
  ERROR: Could not find a version that satisfies the requirement bs4==4.7.1 (from -r requirements.txt (line 5)) (from versions: 0.0.0, 0.0.1)
ERROR: No matching distribution found for bs4==4.7.1 (from -r requirements.txt (line 5))

**Comment by danz0l** [comment]
tried the following

 pip install beautifulsoup4

Shows that on my build i already have beautiful soup 4.6.0. installed and thats current ?

Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (4.6.0)

**Comment by Ahsome** [comment]
Yup, found the issue. Go to settings.ini and change `bs4` to `beautifulsoup4`. This should fix the problem

**Comment by danz0l** [comment]
i ran the code anyways and looks likely youve hardcoded the python location for windows in your script ?

On running the code i get

A Wizard's Tale (2018)
sh: 1: C:/Python27/python.exe: not found
A Few Good Men (1992)
sh: 1: C:/Python27/python.exe: not found
After Earth (2013)
sh: 1: C:/Python27/python.exe: not found
A Million Happy Nows (2017)
sh: 1: C:/Python27/python.exe: not found

Obviously using unix exe files and that kinda path are not applicable

**Comment by Ahsome** [comment]
I swear, V2 must have have removed that, I'm not sure why is stayed. Let me try attaching one last time...

**Comment by danz0l** [comment]
OK modifying the requirements brings up a further error

~/Trailer-Downloader-Test$ python -m pip install -r requirements.txt

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: tmdbsimple==2.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: youtube-dl==2019.4.24 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2019.4.24)
Requirement already satisfied: ffmpeg==1.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (1.4)
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.22.0)
Collecting beautifulsoup4==4.7.1 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl (94kB)
     |████████████████████████████████| 102kB 170kB/s
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0->-r requirements.txt (line 4)) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0->-r requirements.txt (line 4)) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests==2.22.0->-r requirements.txt (line 4)) (2.8)
Collecting soupsieve>=1.2 (from beautifulsoup4==4.7.1->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/b9/a5/7ea40d0f8676bde6e464a6435a48bc5db09b1a8f4f06d41dd997b8f3c616/soupsieve-1.9.1-py2.py3-none-any.whl
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4==4.7.1->-r requirements.txt (line 5)) (1.5)
Installing collected packages: soupsieve, beautifulsoup4
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/soupsieve'
Consider using the `--user` option or check the permissions.

**Comment by danz0l** [comment]
scratch last comment. Running sudo to retain file permissions sorted it

**Comment by Ahsome** [comment]
**V3: Hopefully Fixed Edition**
[Trailer-Downloader.zip](https://github.com/airship-david/Trailer-Downloader/files/3305378/Trailer-Downloader.zip)

**Comment by danz0l** [comment]
unfortunately not. Something now broke 

python Trailer-Downloader-Test/download_all.py --directory /media/xxxxxx/z/Movies/1/
  File "Trailer-Downloader-Test/download_all.py", line 99
    main())
          ^
SyntaxError: invalid syntax

**Comment by Ahsome** [comment]
Was this from V3

**Comment by danz0l** [comment]
yes.

**Comment by Ahsome** [comment]
```
python.exe download_all.py --directory "C:\Users\XXXXX\Documents\GitHub\Trailer-Downloader\Movies"
```
This worked for me, whether on both Python 2 and 3. Can you make sure the location of python in settings.ini is correct?

**Comment by danz0l** [comment]
yes its correct.

Replacing the original downlolad_all from mikes build over the v3 restores downloads completely and functions as it should and most trailers downloaded. Did you alter any code in downloads_all ?

After it finished i got

Trailer-Downloader-Test/download_all.py --directory /media/xxxx/z/Movies/1/
A Wizard's Tale (2018)
A Few Good Men (1992)
After Earth (2013)
A Million Happy Nows (2017)
Traceback (most recent call last):
  File "/home/xxxx/Trailer-Downloader-Test/download.py", line 315, in <module>
    main()
  File "/home/xxxx/Trailer-Downloader-Test/download.py", line 266, in main
    video = getMovieLink(arguments['title'])
  File "/home/xxxx/Trailer-Downloader-Test/findYoutubeLink.py", line 32, in getMovieLink
    link = soup.findAll('div', attrs={'class':'yt-lockup yt-lockup-tile yt-lockup-movie-vertical-poster vve-check clearfix yt-uix-tile'})[0]['data-context-item-id']
IndexError: list index out of range

I put xxxx in where security might be an issue posting to an open forum

**Comment by danz0l** [comment]
Think that will be an error brought up because it doesnt appear that youtube have "A million Happy Nows (2017)" to rent

**Comment by Ahsome** [comment]
Yup that's exactly it, I will have to place a check to ignore files if they are not on youtube. This should be easy, just ignore if an IndexError is thrown!

**Comment by Ahsome** [comment]
Edited files:
[Trailer-Downloader.zip](https://github.com/airship-david/Trailer-Downloader/files/3305516/Trailer-Downloader.zip)

Replace download.py and findYoutubeLink.py with the ones with the zip, and the error should stop

**Comment by Ahsome** [comment]
Did the rest download OK? I'm curious if the quality is good

**Comment by Ahsome** [comment]
I need to stop touching buttons

**Comment by danz0l** [comment]
will test now.

Running further i see there is going to be a need to check the trailers afterwards manually.

camp x ray (2016)
braveheart (1995) 

both works as they should. However youtube have used excerpts of the movie in favour of actual trailers (aka itunes and google play as reported previously) rendering the trailer kinda mute.

But yes, of those that downloaded successfully, ALL the downloads were in great quality and reached my 1080p high rate settings in settings.ini

**Comment by Ahsome** [comment]
I just tested with Braveheart (1995). I got a proper trailer (albeit long), but it has background commentary. Did you not get this?

And I'm SO glad the downloads that did work were in great quality. Curious to do some testing on 4K videos

**Comment by danz0l** [comment]
still an error on ones not available using updated script

python Trailer-Downloader-Test/download_all.py --directory /media/Proliant/z/Movies/1/
Captive State (2019)
Traceback (most recent call last):
  File "/home/xbmc/Trailer-Downloader-Test/download.py", line 317, in <module>
    main()
  File "/home/xbmc/Trailer-Downloader-Test/download.py", line 273, in main
    if file:
UnboundLocalError: local variable 'file' referenced before assignment
Bullet to the Head (2013)
Traceback (most recent call last):
  File "/home/xbmc/Trailer-Downloader-Test/download.py", line 317, in <module>
    main()
  File "/home/xbmc/Trailer-Downloader-Test/download.py", line 273, in main
    if file:
UnboundLocalError: local variable 'file' referenced before assignment
Catch Me If You Can (2002)
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Camp X-Ray (2014)
Braveheart (1995)
Cast Away (2000)

Just checked braveheart again and its definately just the start of the movie and is using this landing page
https://www.youtube.com/watch?v=CE0Nw-LvQlE

Further to add, Castaway isnt an officual trialer but looks like a set of video clips from the movie combined to make a trailer like appearance (obviously edited by youtube) with, believe it or not, the braveheart main music playing in the background LOL

**Comment by danz0l** [comment]
still an error on ones not available using updated script

python Trailer-Downloader-Test/download_all.py --directory /media/xxxx/z/Movies/1/
Captive State (2019)
Traceback (most recent call last):
File "/home/xxxx/Trailer-Downloader-Test/download.py", line 317, in 
main()
File "/home/xxxx/Trailer-Downloader-Test/download.py", line 273, in main
if file:
UnboundLocalError: local variable 'file' referenced before assignment
Bullet to the Head (2013)
Traceback (most recent call last):
File "/home/xbmc/Trailer-Downloader-Test/download.py", line 317, in 
main()
File "/home/xbmc/Trailer-Downloader-Test/download.py", line 273, in main
if file:
UnboundLocalError: local variable 'file' referenced before assignment
Catch Me If You Can (2002)
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Camp X-Ray (2014)
Braveheart (1995)
Cast Away (2000)

Just checked braveheart again and its definately just the start of the movie and is using this landing page
https://www.youtube.com/watch?v=CE0Nw-LvQlE

Further to add, Castaway isnt an officual trialer but looks like a set of video clips from the movie combined to make a trailer like appearance (obviously edited by youtube) with, believe it or not, the braveheart main music playing in the background LOL

**Comment by Ahsome** [comment]
Rename .txt to .py. Looks like a rookie mistake on my part, whoops
[download.txt](https://github.com/airship-david/Trailer-Downloader/files/3305629/download.txt)

And WHAT
Okay I think something about the code has somehow merged the main theme from Braveheart trailer, into the Castaway trailer LMAO

**Comment by danz0l** [comment]
no the file you attached on v4 was a .py extnsion

and no, the code isnt mnerging, its just how youtube has it.

https://www.youtube.com/watch?v=0x2IIYmZgoQ

II just found it funny that they are using bravehearts music in the castaway trailer they created. I wonder how they got around that copyright LOL

**Comment by Ahsome** [comment]
That's even more funny, how in the world did that happen 🤣🤣🤣

Also yup but it made a mistake, so I sent a V5, just as a .txt because GitHub does not allow me to attach .py 😑

**Comment by Ahsome** [comment]
What I find interesting is that your links for the trailers do not open on my side. I think the links are always specific to the individual person watching it, but luckily the code still somehow works

**Comment by danz0l** [comment]
Ah will try that now.

However I'm not fully convinced we are going in the right direction for this now. If from the very brief test, YouTubes practice of movie excerpts for their trailers is the norm, our libraries could end with lots of potential non needed clutter that really serves little purpose. A trailer to most will be a breath introduction to the entire story, most of which would never be covered in an excerpt (camp x ray is a classic example of this), so this may not be a feasible 3rd location for trailers. What do you think ?

**Comment by danz0l** [comment]
Regards your last comment, this could be a region specific thing perhaps ? Where abouts are you located ?

**Comment by Ahsome** [comment]
I am located in Australia! I have to ask, with your trailer for Cast Away, does it show a trailer with voice over in the background? When I downloaded Cast Away (200), I get a 2 minute 30 second trailer with voice over in the background, where he says "In an ordinary life..."

Do you get this?

**Comment by danz0l** [comment]
That's the one. It's a curated YouTube trailer, not the actual trailer

The original trailer can be seen at this link

https://youtu.be/PJvosb4UCLs

They most certainly likely wouldn't have had the copyright for the brave heart music to be played under the narrative.

**Comment by danz0l** [comment]
Sorry I'm totally totally mistaken. The original theatrical trailer DOES use the braveheart music lol

**Comment by Ahsome** [comment]
Hmm, what should we do in this scenario? The curated trailer is a lot higher quality, even if its not the original trailer that came from the film

**Comment by danz0l** [comment]
Interesting to see that YouTube are using fan trailers through their rental system. Didn't think they would do that

**Comment by Ahsome** [comment]
Anything to make their life easier...

**Comment by danz0l** [comment]
I agree, this particular trailer isn't a bad example, although it goes around the houses to explain why he's on the island in the first place. For me, the theatrical trailer gets to the point quickly.

Let me do further testing

**Comment by danz0l** [comment]
on a side note, error handling is working properly now on v5 apart from detecting a 404 error

Catch Me If You Can (2002)
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Ahsome** [comment]
Looks like that, for some ungodly reason, Catch Me If You Can (2002) does exist on YouTube Movies but does not have a trailer that plays (even they get tired apparently). I'll try fixing this right now

**Comment by Ahsome** [comment]
This should now prevent you from downloading assuming there is no trailer:
[findYoutubeLink.txt](https://github.com/airship-david/Trailer-Downloader/files/3305816/findYoutubeLink.txt)

**Comment by danz0l** [comment]
ok further testing reveals some interesting results

the code is indeed downloading trailers very well. As in, its matching those movies to the youtube rental trailers perfectly.

Also, when it does, the quality is extremely good.

Lets take Wildling (2018) as an example.

I had already previously downloaded a trailer for this movie. I'm not sure if I used this script to do so as I was manually downloading through youtube prior to using the script. Here are my findings

> 

original trailer.mkv
==============

Filesize : 15.0 MB 

Video :
frame width : 1920
frame heigh : 1080
Data Rate : 701kbps
Total Bitrate : 826kbps

Audio:
bitrate : 125kbps
channels : 2
audio sample rate : 44.100 khz

> 

Downloaded Trailer from Youtube Rental
===========================
Filesize : 57.0 MB

Video :
frame width : 1920
frame heigh : 1080
Data Rate : 3204kbps
Total Bitrate : 3587kbps

Audio:
bitrate : 383kbps
channels : 6
audio sample rate : 48.000 khz

Thats a massive difference in quality and provides surround sound.

Not all show such huge improvements but a lot certainly do show quality improvements on testing.

However Youtube sometimes rely on fan trailers to improve their quality if they cant source an original trailer it seems. This isn't quite as drastic in my short testing as I had originally first thought, having 1 in each 6 movie testing so the addition is certainly of benefit.

What I would suggest however is that users have the options to enable or disable the source of the trailer downloads. Apple, Youtube via TMDB and now obviously Youtube via Youtube Rentals.

**Comment by Ahsome** [comment]
That is actually such a massive difference, both in terms of quality and the introduction of surround sound. This is perfect! I think this YouTube scraper will work a lot better with new Movies coming forward, given they will have the full support of YouTube behind them

Now I'll just focusing on tidying up the script, including actual checking for Title. It looks like it's not needed, but better to be safe. It should be pretty trivial to allow enabling and disabling of multiple sources via settings.ini, just need to confirm with @airship-david 

Any other possible feature requests you'd like?

**Comment by danz0l** [comment]
I was wondering, based on Davids original comments on TMDB, whether we could implement an upload to TMDB based on quality.

I dont know if the tmdbs API would allow for such things, but i see it like this.

When a user downloads a trailer from the script, it checks through, on the TMDB API to see if it is an upgrade to what they have (Based purely on filesize i would imagine) and if it is it submits this trailer to them for inclusion for others to download and enjoy. This helps the community in the longterm as one person would need to issue the trailer request and others then benefit from it. Obviously this option, if at all feasible, really should be under user guidiance, i.e. they should have the option of turning it on or off as they see fit. Just a thought.

**Comment by Ahsome** [comment]
That would actually be amazing, have the ability to have everyone contribute and improve the overall source. The only problem is that TMDb does not actually host any trailers themselves, but rather only hold links to YouTube videos with them. So the best it could do is upload a link to the YouTube Rental.

Do you know any other sources that accept files directly to upload?

**Comment by danz0l** [comment]
ah yes of course it does. No unfortunately i cant think of a website that does that.

**Comment by Ahsome** [comment]
That sucks :(. Would have been a way to keep this stuff alive

Sidenote, other possible scrapers such as iMDB and RottenTomatoes are also technically possible, but I'm not sure if they're needed at this point

**Comment by danz0l** [comment]
imdb used to be the trailer addicts point of origin but im not convinced they are as good as they used to be.

One other improvement would be cosmetic and only related to download_alll and that would be to clean up the output and report better. If youve ever used smloadr through headless i love how they show the updates through the command line. I'd love to see the movie being searched alongside if it found it and from what source. All on one line.

**Comment by Ahsome** [comment]
Not going to lie, just had a quick peek, their interface looks _gorgeous_. Legit salivating just looking at it. I'd love to implement that in download_all.py, would look amazing. What I'll do is wait for all the pull requests for features be merged. After that's done, it'll be a lot easier to edit download_all.py. Otherwise, currently every feature is broken off into multiple branches and it would be living _hell_ to edit it

**Comment by airship-david** [comment]
This looks very promising. One thing I noticed is that 'html5lib' in the youtube_rental.py file needs to be changed to 'html.parser' or it throws an error on my machine (easy change). I have created a new branch called rewrite and I starting breaking out the functions into different files in the lib folder. I also removed the need to call the download script from download_all. Would it be possible for you to wrap this code into that branch? The rewrite branch is honestly pretty messy in it's current form and it doesn't come close to meeting my standards for simplification but I am thinking that we can use that branch to incorporate features like this and keep improving things until we eventually arrive at the next version. As long as we stick to only doing one thing at a time, we'll keep things tidy and avoid conflicts. Thanks!

**Comment by Ahsome** [comment]
Yup that sounds awesome! A good rewrite I think is what this script needs in general (it was odd that _all just called download directly). I've been a bit busy with work recently, but once that's over i'll contribute to the rewrite!

**Pull request closed without merging**
